#!/bin/bash
set -eux

VERSION="2.1.2"

cp -r agnocast_kmod agnocast-kmod-v${VERSION}-${VERSION}
tar czf agnocast-kmod-v${VERSION}_${VERSION}.orig.tar.gz agnocast-kmod-v${VERSION}-${VERSION}

cd agnocast-kmod-v${VERSION}-${VERSION}
debuild -S -sa

# When re-upload with a next release number
# debuild -S -sd

cd ..
rm -rf agnocast-kmod-v${VERSION}-${VERSION}
