#!/bin/bash
set -eux

MAJOR_MINOR="2.0"
PATCH="1"

VERSION="${MAJOR_MINOR}.${PATCH}"

cp -r agnocast_heaphook agnocast-heaphook-v${MAJOR_MINOR}-${VERSION}
tar czf agnocast-heaphook-v${MAJOR_MINOR}_${VERSION}.orig.tar.gz agnocast-heaphook-v${MAJOR_MINOR}-${VERSION}

cd agnocast-heaphook-v${MAJOR_MINOR}-${VERSION}
debuild -S -sa

cd ..
rm -rf agnocast-heaphook-v${MAJOR_MINOR}-${VERSION}
