#!/bin/bash
set -eux

MAJOR_MINOR="2.0"
PATCH="1"
RELEASE="1"

VERSION="${MAJOR_MINOR}.${PATCH}"
CHANGES_FILE="agnocast-kmod-v${MAJOR_MINOR}_${VERSION}-${RELEASE}_source.changes"

dput ppa:t4-system-software/agnocast ${CHANGES_FILE}
