#!/bin/bash

# Setup
rm -rf build/e2e_test install/e2e_test
source /opt/ros/humble/setup.bash
colcon build --symlink-install --packages-select e2e_test --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/setup.bash

# Configurations
CONFIG_FILE="src/e2e_test/test/config_test_1to1_with_ros2sub.yaml"
LAUNCH_PUB_BEFORE_SUB=(true false)
PUB_QOS_DEPTH=(1 10)
PUB_TRANSIENT_LOCAL=(true false)
SUB_QOS_DEPTH=(1 10)
SUB_TRANSIENT_LOCAL=(true false)
USE_TAKE_SUB=(true false)

COUNT=0
for launch_pub_before_sub in ${LAUNCH_PUB_BEFORE_SUB[@]}; do
    for pub_qos_depth in ${PUB_QOS_DEPTH[@]}; do
        for pub_transient_local in ${PUB_TRANSIENT_LOCAL[@]}; do
            for sub_qos_depth in ${SUB_QOS_DEPTH[@]}; do
                for sub_transient_local in ${SUB_TRANSIENT_LOCAL[@]}; do
                    for use_take_sub in ${USE_TAKE_SUB[@]}; do
                        COUNT=$((COUNT + 1))
                        echo "=================== $COUNT / 64 =================="
                        echo "launch_pub_before_sub: $launch_pub_before_sub"
                        echo "pub_qos_depth: $pub_qos_depth"
                        echo "pub_transient_local: $pub_transient_local"
                        echo "sub_qos_depth: $sub_qos_depth"
                        echo "sub_transient_local: $sub_transient_local"
                        echo "use_take_sub: $use_take_sub"
                        echo "=============================================="

                        sed -i "s/launch_pub_before_sub:.*/launch_pub_before_sub: $launch_pub_before_sub/g" $CONFIG_FILE
                        sed -i "s/pub_qos_depth:.*/pub_qos_depth: $pub_qos_depth/g" $CONFIG_FILE
                        sed -i "s/pub_transient_local:.*/pub_transient_local: $pub_transient_local/g" $CONFIG_FILE
                        sed -i "s/sub_qos_depth:.*/sub_qos_depth: $sub_qos_depth/g" $CONFIG_FILE
                        sed -i "s/sub_transient_local:.*/sub_transient_local: $sub_transient_local/g" $CONFIG_FILE
                        sed -i "s/use_take_sub:.*/use_take_sub: $use_take_sub/g" $CONFIG_FILE
                        launch_test src/e2e_test/test/test_1to1_with_ros2sub.py

                        if [ $? -ne 0 ]; then
                            echo "Test failed"
                            exit 1
                        fi
                    done
                done
            done
        done
    done
done
echo "All tests passed"

# Reset config file
git checkout -- "$CONFIG_FILE"
