#!/bin/bash

# Setup
rm -rf build/e2e_test install/e2e_test
colcon build --symlink-install --packages-select e2e_test --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/setup.bash

# Configurations
CONFIG_FILE="src/e2e_test/test/config_test_1to1_with_ros2sub.yaml"
LAUNCH_PUB_BEFORE_SUB=(true false)
PUB_QOS_DEPTH=(1 10)
PUB_TRANSIENT_LOCAL=(true false)
SUB_QOS_DEPTH=(1 10)
SUB_TRANSIENT_LOCAL=(true false)
USE_TAKE_SUB=(true false)

COUNT=0
for LAUNCH_PUB_BEFORE_SUB in ${LAUNCH_PUB_BEFORE_SUB[@]}; do
    for PUB_QOS_DEPTH in ${PUB_QOS_DEPTH[@]}; do
        for PUB_TRANSIENT_LOCAL in ${PUB_TRANSIENT_LOCAL[@]}; do
            for SUB_QOS_DEPTH in ${SUB_QOS_DEPTH[@]}; do
                for SUB_TRANSIENT_LOCAL in ${SUB_TRANSIENT_LOCAL[@]}; do
                    for USE_TAKE_SUB in ${USE_TAKE_SUB[@]}; do
                        COUNT=$((COUNT + 1))
                        echo "=================== $COUNT / 64 =================="
                        echo "launch_pub_before_sub: $LAUNCH_PUB_BEFORE_SUB"
                        echo "pub_qos_depth: $PUB_QOS_DEPTH"
                        echo "pub_transient_local: $PUB_TRANSIENT_LOCAL"
                        echo "sub_qos_depth: $SUB_QOS_DEPTH"
                        echo "sub_transient_local: $SUB_TRANSIENT_LOCAL"
                        echo "use_take_sub: $USE_TAKE_SUB"
                        echo "=============================================="

                        sed -i "s/launch_pub_before_sub:.*/launch_pub_before_sub: $LAUNCH_PUB_BEFORE_SUB/g" $CONFIG_FILE
                        sed -i "s/pub_qos_depth:.*/pub_qos_depth: $PUB_QOS_DEPTH/g" $CONFIG_FILE
                        sed -i "s/pub_transient_local:.*/pub_transient_local: $PUB_TRANSIENT_LOCAL/g" $CONFIG_FILE
                        sed -i "s/sub_qos_depth:.*/sub_qos_depth: $SUB_QOS_DEPTH/g" $CONFIG_FILE
                        sed -i "s/sub_transient_local:.*/sub_transient_local: $SUB_TRANSIENT_LOCAL/g" $CONFIG_FILE
                        sed -i "s/use_take_sub:.*/use_take_sub: $USE_TAKE_SUB/g" $CONFIG_FILE
                        launch_test src/e2e_test/test/test_1to1_with_ros2sub.py

                        if [ $? -ne 0 ]; then
                            echo "Test failed"
                            exit 1
                        fi
                    done
                done
            done
        done
    done
done
echo "All tests passed"

# Reset config file
sed -i "s/launch_pub_before_sub:.*/launch_pub_before_sub: true/g" $CONFIG_FILE
sed -i "s/pub_qos_depth:.*/pub_qos_depth: 10/g" $CONFIG_FILE
sed -i "s/pub_transient_local:.*/pub_transient_local: true/g" $CONFIG_FILE
sed -i "s/sub_qos_depth:.*/sub_qos_depth: 10/g" $CONFIG_FILE
sed -i "s/sub_transient_local:.*/sub_transient_local: true/g" $CONFIG_FILE
sed -i "s/use_take_sub:.*/use_take_sub: true/g" $CONFIG_FILE
