name: auto assign author to assignee

on:
  pull_request:
    types: opened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to assignee on PR
        uses: technote-space/assign-author@v1
