name: build-and-test-heaphook

on:
  pull_request:
    types:
      - labeled

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-heaphook:
    if: ${{ github.event.label.name == 'run-build-test' }}
    runs-on: ubuntu-22.04

    steps:
    - name: Set PR fetch depth
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}

    - name: Check for agnocast_heaphook changes
      id: check_changes
      run: |
        if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^agnocast_heaphook/'; then
          echo "agnocast_heaphook changed"
          echo "heaphook_changed=true" >> $GITHUB_OUTPUT
        else
          echo "No agnocast_heaphook changed"
          echo "heaphook_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Rust environment
      if: steps.check_changes.outputs.heaphook_changed == 'true'
      run: |
        rustup toolchain install 1.85.0
        rustup default 1.85.0
        rustup component add clippy rustfmt

    - name: Run rustfmt on agnocast_heaphook
      if: steps.check_changes.outputs.heaphook_changed == 'true'
      run: |
        cd agnocast_heaphook
        cargo fmt && git diff --exit-code

    - name: Run clippy on agnocast_heaphook
      if: steps.check_changes.outputs.heaphook_changed == 'true'
      run: |
        cd agnocast_heaphook
        cargo clippy -- --deny warnings

    - name: Build agnocast_heaphook
      if: steps.check_changes.outputs.heaphook_changed == 'true'
      run: |
        cd agnocast_heaphook
        cargo build --release
